# Generated by Django 5.2.15 on 2026-06-28 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notificacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=100, verbose_name="título")),
                ("mensagem", models.TextField(verbose_name="mensagem")),
                (
                    "criada_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="criada em"),
                ),
                (
                    "enviada_em",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="enviada em"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("rascunho", "Rascunho"),
                            ("enviada", "Enviada"),
                            ("erro", "Erro parcial"),
                        ],
                        default="rascunho",
                        max_length=10,
                        verbose_name="status",
                    ),
                ),
                (
                    "total_enviadas",
                    models.PositiveIntegerField(default=0, verbose_name="entregas OK"),
                ),
                (
                    "total_erros",
                    models.PositiveIntegerField(default=0, verbose_name="erros"),
                ),
            ],
            options={
                "verbose_name": "notificação",
                "verbose_name_plural": "notificações",
                "ordering": ["-criada_em"],
            },
        ),
        migrations.AddField(
            model_name="profile",
            name="notificacoes_ativas",
            field=models.BooleanField(
                default=True,
                help_text="Quando desativado, o usuário não recebe push notifications.",
                verbose_name="notificações ativas",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="push_token",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Expo Push Token do dispositivo. Preenchido automaticamente pelo app.",
                max_length=200,
                verbose_name="token de notificação",
            ),
        ),
    ]
