# Generated by Django 5.2.15 on 2026-07-06 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_push_notifications"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificacao",
            name="agendada_para",
            field=models.DateTimeField(
                blank=True,
                help_text='Deixe em branco para enviar na hora. Preencha e use a ação "Agendar envio" para disparar automaticamente nesta data/hora.',
                null=True,
                verbose_name="agendar para",
            ),
        ),
        migrations.AlterField(
            model_name="notificacao",
            name="status",
            field=models.CharField(
                choices=[
                    ("rascunho", "Rascunho"),
                    ("agendada", "Agendada"),
                    ("enviada", "Enviada"),
                    ("erro", "Erro parcial"),
                ],
                default="rascunho",
                max_length=10,
                verbose_name="status",
            ),
        ),
    ]
