# Generated by Django 6.0.6 on 2026-07-06 19:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_notificacao_agendada_para_alter_notificacao_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_hash', models.CharField(max_length=128)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('expira_em', models.DateTimeField()),
                ('usado', models.BooleanField(default=False)),
                ('tentativas', models.PositiveIntegerField(default=0)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codigos_reset', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'código de recuperação',
                'verbose_name_plural': 'códigos de recuperação',
                'ordering': ['-criado_em'],
            },
        ),
    ]
