# Generated by Django 6.0.6 on 2026-07-15 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_passwordresetcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assinatura',
            fields=[
            ],
            options={
                'verbose_name': 'assinatura',
                'verbose_name_plural': 'assinaturas',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.profile',),
        ),
        migrations.AddField(
            model_name='profile',
            name='premium_manual',
            field=models.BooleanField(default=False, help_text='Liga o Premium manualmente (comp/brinde), sem pagamento.', verbose_name='premium (concedido)'),
        ),
        migrations.AddField(
            model_name='profile',
            name='premium_manual_ate',
            field=models.DateField(blank=True, help_text='Opcional. Vazio = permanente; com data = expira nesse dia.', null=True, verbose_name='premium manual até'),
        ),
        migrations.AddField(
            model_name='profile',
            name='premium_pago_ate',
            field=models.DateTimeField(blank=True, help_text='Validade da assinatura paga (sincronizada do RevenueCat).', null=True, verbose_name='premium pago até'),
        ),
        migrations.AddField(
            model_name='profile',
            name='rc_ultimo_evento',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name='último evento RevenueCat'),
        ),
    ]
