# Generated by Django 6.0.6 on 2026-06-23 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(db_index=True, unique=True, verbose_name='número')),
                ('titulo', models.CharField(max_length=200, verbose_name='título')),
                ('versiculo_texto', models.TextField(verbose_name='versículo-chave (texto)')),
                ('versiculo_ref', models.CharField(blank=True, max_length=120, verbose_name='referência do versículo')),
                ('reflexao', models.TextField(help_text='Cada linha em branco separa um parágrafo.', verbose_name='reflexão')),
                ('oracao', models.TextField(verbose_name='oração')),
                ('aplicacao', models.TextField(verbose_name='aplicação prática')),
                ('frase_guardar', models.TextField(verbose_name='frase para guardar no coração')),
                ('referencias', models.TextField(blank=True, help_text='Uma referência por linha.', verbose_name='referências bíblicas complementares')),
                ('audio', models.FileField(blank=True, help_text='Suba o MP3 da narração. Enquanto estiver vazio, o app não mostra o botão Ouvir.', null=True, upload_to='audios/', verbose_name='áudio (narração)')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='imagens/', verbose_name='imagem/ilustração')),
                ('audio_acesso', models.CharField(choices=[('free', 'Gratuito'), ('premium', 'Premium (assinantes)')], default='premium', help_text='Capítulos 1 e 2 = Gratuito. Do 3 em diante = Premium. (A leitura é sempre livre.)', max_length=10, verbose_name='acesso ao áudio')),
                ('publicado', models.BooleanField(default=True, help_text='Desmarque para esconder do app.', verbose_name='publicado')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
            ],
            options={
                'verbose_name': 'capítulo',
                'verbose_name_plural': 'capítulos',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='SpecialPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='título')),
                ('conteudo', models.TextField(verbose_name='conteúdo')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='ordem')),
                ('publicado', models.BooleanField(default=True, verbose_name='publicado')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
            ],
            options={
                'verbose_name': 'página especial',
                'verbose_name_plural': 'páginas especiais',
                'ordering': ['ordem', 'id'],
            },
        ),
    ]
