# Generated by Django 5.2.15 on 2026-07-06 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LembreteTexto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "texto",
                    models.CharField(
                        help_text="Mensagem curta e acolhedora (ex.: 'Reserve um tempo com Deus hoje ☕').",
                        max_length=200,
                        verbose_name="texto do lembrete",
                    ),
                ),
                (
                    "ativo",
                    models.BooleanField(
                        default=True,
                        help_text="Desmarque para tirar esta frase do rodízio.",
                        verbose_name="ativo",
                    ),
                ),
                ("ordem", models.PositiveIntegerField(default=0, verbose_name="ordem")),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
            ],
            options={
                "verbose_name": "texto de lembrete",
                "verbose_name_plural": "textos de lembrete",
                "ordering": ["ordem", "id"],
            },
        ),
    ]
