# Generated by Django 5.2.15 on 2026-07-06 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0002_lembretetexto"),
    ]

    operations = [
        migrations.CreateModel(
            name="Produto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=120, verbose_name="nome")),
                ("descricao", models.TextField(blank=True, verbose_name="descrição")),
                (
                    "preco",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Opcional. Deixe em branco para não mostrar o preço.",
                        max_digits=8,
                        null=True,
                        verbose_name="preço",
                    ),
                ),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("livro", "Livro"),
                            ("xicara", "Xícara"),
                            ("camiseta", "Camiseta"),
                            ("outro", "Outro"),
                        ],
                        default="outro",
                        max_length=10,
                        verbose_name="categoria",
                    ),
                ),
                (
                    "imagem",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="produtos/",
                        verbose_name="imagem",
                    ),
                ),
                (
                    "link_compra",
                    models.URLField(
                        blank=True,
                        help_text="Opcional (para o futuro). Enquanto vazio, o app mostra 'Em breve'.",
                        verbose_name="link de compra",
                    ),
                ),
                (
                    "destaque",
                    models.BooleanField(
                        default=False,
                        help_text="Marque para dar evidência (ex.: o livro físico no topo da loja).",
                        verbose_name="destaque",
                    ),
                ),
                ("ordem", models.PositiveIntegerField(default=0, verbose_name="ordem")),
                (
                    "publicado",
                    models.BooleanField(
                        default=True,
                        help_text="Desmarque para esconder da loja.",
                        verbose_name="publicado",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
            ],
            options={
                "verbose_name": "produto",
                "verbose_name_plural": "produtos",
                "ordering": ["-destaque", "ordem", "id"],
            },
        ),
    ]
