# Generated by Django 5.2.15 on 2026-07-06 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0003_produto"),
    ]

    operations = [
        migrations.CreateModel(
            name="Banner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "titulo",
                    models.CharField(
                        blank=True,
                        help_text="Texto do banner quando não houver imagem (ex.: 'Conheça a Loja').",
                        max_length=120,
                        verbose_name="título",
                    ),
                ),
                (
                    "subtitulo",
                    models.CharField(
                        blank=True,
                        help_text="Linha de apoio abaixo do título.",
                        max_length=200,
                        verbose_name="subtítulo",
                    ),
                ),
                (
                    "imagem",
                    models.ImageField(
                        blank=True,
                        help_text="Opcional. Se enviar uma arte, ela aparece no lugar do texto.",
                        null=True,
                        upload_to="banners/",
                        verbose_name="imagem",
                    ),
                ),
                (
                    "destino",
                    models.CharField(
                        choices=[
                            ("loja", "Abrir a Loja"),
                            ("link_externo", "Abrir um link externo"),
                            ("capitulo", "Abrir um capítulo"),
                            ("nenhum", "Não clicável"),
                        ],
                        default="loja",
                        max_length=15,
                        verbose_name="destino do toque",
                    ),
                ),
                (
                    "link_externo",
                    models.URLField(
                        blank=True,
                        help_text="Usado quando o destino é 'link externo'.",
                        verbose_name="link externo",
                    ),
                ),
                (
                    "capitulo_numero",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Usado quando o destino é 'abrir um capítulo'.",
                        null=True,
                        verbose_name="número do capítulo",
                    ),
                ),
                (
                    "ativo",
                    models.BooleanField(
                        default=True,
                        help_text="O app mostra o primeiro banner ativo (pela ordem). Desmarque para esconder.",
                        verbose_name="ativo",
                    ),
                ),
                ("ordem", models.PositiveIntegerField(default=0, verbose_name="ordem")),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
            ],
            options={
                "verbose_name": "banner",
                "verbose_name_plural": "banners",
                "ordering": ["ordem", "id"],
            },
        ),
    ]
