# Generated by Django 6.0.6 on 2026-07-12 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicaFundo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120, verbose_name='título')),
                ('arquivo', models.FileField(upload_to='musicas/', verbose_name='arquivo de áudio')),
                ('ativa', models.BooleanField(default=True, help_text='Desmarque para tirar esta faixa do app.', verbose_name='ativa')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='ordem')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
            ],
            options={
                'verbose_name': 'música de fundo',
                'verbose_name_plural': 'músicas de fundo',
                'ordering': ['ordem', 'id'],
            },
        ),
    ]
