# Generated by Django 6.0.6 on 2026-07-18 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_musicafundo'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialpage',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='paginas/', verbose_name='áudio (narração)'),
        ),
        migrations.AddField(
            model_name='specialpage',
            name='subtitulo',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='subtítulo'),
        ),
    ]
